# Generated by Django 3.2.16 on 2022-10-31 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
