# Generated by Django 3.2.16 on 2022-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221031_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Исследование', 'verbose_name_plural': 'Исследования'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='published_date',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Активно', max_length=15, verbose_name='Статус'),
        ),
    ]
