# Generated by Django 3.2.16 on 2022-11-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221031_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='numbers',
            field=models.PositiveSmallIntegerField(blank=True, default='1'),
        ),
    ]
