# Generated by Django 3.2.16 on 2022-11-05 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='documents/', verbose_name='Файл')),
                ('numbers', models.PositiveSmallIntegerField(default='1', verbose_name='Номер')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('status', models.CharField(default='Активно', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(default='', upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='numbers',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Номер'),
        ),
    ]
