# Generated by Django 3.2.16 on 2022-11-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221105_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_auto',
            old_name='created_date',
            new_name='created_date_a',
        ),
        migrations.RenameField(
            model_name='task_auto',
            old_name='file',
            new_name='file_a',
        ),
        migrations.RenameField(
            model_name='task_auto',
            old_name='numbers',
            new_name='numbers_a',
        ),
        migrations.RenameField(
            model_name='task_auto',
            old_name='status',
            new_name='status_a',
        ),
        migrations.RenameField(
            model_name='task_auto',
            old_name='title',
            new_name='title_a',
        ),
    ]
